[package]
name = "aoc-helper"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.5", features = ["extra-traits", "full"] }
quote = "1.0.2"
proc-macro2 = "1.0.5"
proc-macro-error = "1.0.4"
itertools = "0.10.5"
